# Generated by Django 3.2.9 on 2021-11-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlapp',
            name='description',
            field=models.TextField(default='this is cool'),
        ),
        migrations.AddField(
            model_name='mlapp',
            name='title',
            field=models.TextField(default='this is cool'),
        ),
    ]
